services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Porta de administração
      - "5672:5672" # Porta padrão de mensageria
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter
    environment:
      RABBITMQ_URI: "http://user:password@rabbitmq:5672"
    ports:
      - "15692:15692" # Porta para expor as métricas
    networks:
      - app_network

  # backend:
  #   build: ./backend
  #   container_name: node-backend
  #   depends_on:
  #     - rabbitmq
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - app_network

volumes:
  rabbitmq_data:
  prometheus_data:

networks:
  app_network:
    driver: bridge
