global:
  scrape_interval: 10s  # Intervalo para coleta de métricas (10 segundos)

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']  # RabbitMQ exporter (porta padrão do Prometheus)
      
  - job_name: 'nodejs'
    static_configs:
      - targets: ['nodejs:9100']  # Endereço do seu servidor Node.js para métricas
